### ISSUE TITLE
Diffs aren't always saved

### ISSUE THREAD

**Issue by toupeira** [angular-seattle/blue-harvest#14]
I've noticed that blue-harvest doesn't always save the diff images even though it outputs a message saying they were, looking into it I noticed that `looks-same` does some funky stuff with `setImmediate` which explains the behaviour I was seeing, e.g. nothing saved if the e2e run finishes quickly, or only the first image being saved.

**Comment by awang-copperleaf** [comment]
Same happened to me when a screenshot test is the last one in a test suite. I have thus avoided that and it works just fine for now

**Comment by awang-copperleaf** [comment]
oops, it seems that when I updated code for `compareScreenshot()` I did not handle the callback well, so there is a chance that your code got into the race condition and failed to wait for the images to be saved. I will raise a pr on a fix for this issue, Sorry for the inconvenience!

**Comment by SimonNodel-AI** [comment]
Can you guys please do a release with this fix?  Thank you.

**Comment by heathkit** [comment]
Done!
