### ISSUE TITLE
missing feature on mask

### ISSUE THREAD

**Issue by FabienDehopre** [angular-seattle/blue-harvest#8]
There are some missing feature and/or bug with the `addMask` function:
- if the element we want to mask has a z-index greater than 0, the mask is not visible since it's under the element we want to hide
- if the element is "dynamically" added, it seems that the element is not found and the mask is not added
- to remove the mask, one needs to execute the following script manually `document.body.removeChild(document.querySelector('#BP_ELEMENT_HIGHLIGHT__'))`. Maybe it would be a good idea to add a `removeMask` function
- for the moment, if you add multiple mask, all the mask elements will have the same id which is not great and if you want to remove one of the mask it is not possible. Maybe the mask should not have an id but a class and the `addMask` function should allow one to specify a suffix for the class name (same for the `removeMask`)

**Comment by awang-copperleaf** [comment]
Hi, please check out #12 on `addMask` and `removeMask` related improvements. I have also documented the usage in `README` if you don't feel like reading code :)

**Comment by SimonNodel-AI** [comment]
can be closed now
